# Generated by Django 2.2.24 on 2021-06-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_DEPARTAMENTO', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_ENTIDAD', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_MUNICIPIO', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('ID_BENEFICIARIO', models.AutoField(primary_key=True, serialize=False)),
                ('DUI_BENEFICIARIO', models.CharField(max_length=10)),
                ('NOMBRE_BENEFICIARIO', models.CharField(max_length=20)),
                ('APELLIDO_BENEFICIARIO', models.CharField(max_length=20)),
                ('DIRECCION_BENEFICIARIO', models.CharField(max_length=100)),
                ('RECEPTOR_BENEFICIARIO', models.BooleanField(choices=[(True, 'Si'), (False, 'No')])),
                ('CANTIDAD', models.IntegerField()),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Principal.Departamento')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Principal.Entidad')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Principal.Municipio')),
            ],
        ),
    ]
